//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int company_id { get; set; }
        public bool is_Active { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> number_of_employees { get; set; }
    }
}
